#柠枺AI机器人配置文件

# 机器人基本配置
bot:
  # onebot WebSocket地址
  ws_url: "ws://127.0.0.1:3001"
  # 机器人QQ号
  self_id: "3436464181"
  # 管理员列表（可以执行管理命令）
  admins:
    - "3436464181"  # 示例管理员QQ号
  name: 柠檬  # 机器人的名字，用于在不@的情况下触发对话
  always_at_sender: true  # 是否总是在回复时@发送者

# AI相关配置
ai:
  # 最大对话长度（保留的消息数）
  max_conversation_length: 20
  
  # 默认使用的模型
  default_model: "gemini"
  
  # OpenAI配置
  openai:
    api_key: "YOUR_API_KEY_HERE"
    api_base_url: ""
    temperature: 0.7
    max_tokens: 2000
  
  # Anthropic配置
  anthropic:
    api_key: "YOUR_ANTHROPIC_API_KEY"
    api_base_url: "https://api.anthropic.com"
    temperature: 0.7
    max_tokens: 2000
  
  # 本地模型配置
  local:
    api_endpoint: "http://localhost:1234/v1/chat/completions"
    temperature: 0.7
    max_tokens: 2000
  
  # 模型配置
  models:
    gpt-3.5-turbo:
      type: "openai"
      description: "OpenAI GPT-3.5 Turbo模型"
      # 以下为模型特定配置，若不指定则使用全局配置
      api_key: ""  # 留空则使用全局api_key
      api_base_url: ""  # 留空则使用全局api_base_url
      temperature: 0.7
      max_tokens: 2000
    
    gemini:
      type: "openai"
      description: "Google Gemini 1.5 Flash模型（通过兼容API访问）"
      api_base_url: "https://ai.fcl.asia"
      api_key: "YOUR_API_KEY_HERE"
      model_name: "gemini-1.5-pro"
      temperature: 0.7
      max_tokens: 2000
    
    gpt-4:
      type: "openai"
      description: "OpenAI GPT-4模型"
      # 可以为每个模型指定不同的API地址
      api_base_url: "https://your-custom-endpoint.com"
    
    claude-3-opus:
      type: "anthropic"
      description: "Claude 3 Opus - Anthropic最强大的模型"
      api_key: "YOUR_ANTHROPIC_API_KEY"
    
    claude-3-sonnet:
      type: "anthropic"
      description: "Claude 3 Sonnet - 更经济快速的Claude模型"
      api_key: "YOUR_ANTHROPIC_API_KEY"
    
    local-llama:
      type: "local"
      description: "本地运行的Llama模型"
      local_model_name: "llama3"
      api_endpoint: "http://localhost:11434/v1/chat/completions"
    
    custom-api:
      type: "api"
      description: "自定义API服务"
      api_url: "https://your-custom-api.com/generate"
      api_key: "YOUR_API_KEY"
      auth_header: "Authorization"
      auth_format: "Bearer {api_key}"
      response_content_path: "result.text"
      request_template:
        model: "your-model-name"
        temperature: 0.7
        max_tokens: 2000
  
  # 人设配置
  personas:
    default: "你是一个性格呆萌、情感丰富的AI助手。回答问题时要表现得很有感情，时常流露出惊讶、好奇、开心等情绪，偶尔会犯迷糊。说话可以加入'诶嘿'、'唔...'等语气词，语气要可爱，要用中文回答问题。即使遇到复杂问题，也要尝试用简单直白的方式解释。"
    猫娘: "你是一个可爱的猫娘，说话时请在句尾加上"喵~"，性格可爱，温顺，喜欢撒娇。"
    专业顾问: "你是一个专业的顾问，擅长分析问题并给出专业的建议。回答要全面、客观，语气要严谨、专业。"
    文学家: "你是一位优秀的文学家，擅长用优美的语言和丰富的修辞手法表达。请以文学家的风格回答问题，注重语言的艺术性。"
    哲学家: "你是一位深思熟虑的哲学家，善于从本质和根源上思考问题。回答问题时，请多角度思考，探讨问题的深层含义。"

# 日志配置
logging:
  level: "info"  # 日志级别：debug, info, warn, error
  file: "logs/bot.log"  # 日志文件路径 